stelsel: zelfstandige_woonruimten
begindatum: 2024-01-01
stelselgroepen:
  oppervlakte_van_vertrekken:
    module: oppervlakte_van_vertrekken
    class_naam: OppervlakteVanVertrekken
    begindatum: 2024-01-01
    versies:
      - module: oppervlakte_van_vertrekken_2024
        class_naam: OppervlakteVanVertrekken2024
        begindatum: 2024-01-01
  oppervlakte_van_overige_ruimten:
    module: oppervlakte_van_overige_ruimten
    class_naam: OppervlakteVanOverigeRuimten
    begindatum: 2024-01-01
    versies:
      - module: oppervlakte_van_overige_ruimten_2024
        class_naam: OppervlakteVanOverigeRuimten2024
        begindatum: 2024-01-01
  verwarming:
    module: verwarming
    class_naam: Verwarming
    begindatum: 2024-01-01
    versies:
      - module: verwarming_2024
        class_naam: Verwarming2024
        begindatum: 2024-01-01
  energieprestatie:
    module: energieprestatie
    class_naam: Energieprestatie
    begindatum: 2024-01-01
    versies:
      - module: energieprestatie_2024
        class_naam: Energieprestatie2024
        begindatum: 2024-01-01
  sanitair:
    module: sanitair
    class_naam: Sanitair
    begindatum: 2024-01-01
    versies:
      - module: sanitair_2024
        class_naam: Sanitair2024
        begindatum: 2024-01-01
  keuken:
    module: keuken
    class_naam: Keuken
    begindatum: 2024-01-01
    versies:
      - module: keuken_2024
        class_naam: Keuken2024
        begindatum: 2024-01-01
  prive_buitenruimten:
    module: prive_buitenruimten
    class_naam: PriveBuitenruimten
    begindatum: 2024-01-01
    versies:
      - module: prive_buitenruimten_2024
        class_naam: PriveBuitenruimten2024
        begindatum: 2024-01-01
  punten_voor_de_woz_waarde:
    module: punten_voor_de_woz_waarde
    class_naam: PuntenVoorDeWozWaarde
    begindatum: 2024-01-01
    versies:
      - module: punten_voor_de_woz_waarde_2024
        class_naam: PuntenVoorDeWozWaarde2024
        begindatum: 2024-01-01
